general.import = [
    "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 1
blur = true

decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 18

#for video
# size = 35.0
